############# HOOKS ########################

# add line numbers
#hook global WinCreate .* %{add-highlighter number_lines -separator ' '}
add-highlighter global/line_numbers number-lines -separator ' '

# add brackets highliting
#hook global WinCreate .* %{add-highlighter show_matching}
add-highlighter global/highlight_matching_brackets show-matching

# add soft wrap
#hook global WinCreate .* %{add-highlighter wrap -word}
add-highlighter global/line_wrap wrap -word

# indent
set global indentwidth 2
set global tabstop 2
#map global insert <tab> '<a-;><gt>'
#map global insert <backtab> '<a-;><lt>'
hook global InsertChar \t %{
    exec -draft -itersel h@
}

# tab completion
hook global InsertCompletionShow .* %{
    map global insert <tab> <c-n>;
    map global insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
    unmap global insert <tab> <c-n>;
    unmap global insert <s-tab> <c-p>
}

# <F2> to make
map global normal <F2> ':w;make<ret>'

# <F3> and <F4> to move between buffers
map global normal <F3> ':buffer-previous<ret>'
map global normal <F4> ':buffer-next<ret>'
